// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vertix/rwa/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AssetStatus is the lifecycle state of an RWA asset.
type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_UNSPECIFIED AssetStatus = 0
	AssetStatus_ASSET_STATUS_DRAFT       AssetStatus = 1
	AssetStatus_ASSET_STATUS_ATTESTED    AssetStatus = 2
	AssetStatus_ASSET_STATUS_ACTIVE      AssetStatus = 3
	AssetStatus_ASSET_STATUS_SETTLED     AssetStatus = 4
)

var AssetStatus_name = map[int32]string{
	0: "ASSET_STATUS_UNSPECIFIED",
	1: "ASSET_STATUS_DRAFT",
	2: "ASSET_STATUS_ATTESTED",
	3: "ASSET_STATUS_ACTIVE",
	4: "ASSET_STATUS_SETTLED",
}

var AssetStatus_value = map[string]int32{
	"ASSET_STATUS_UNSPECIFIED": 0,
	"ASSET_STATUS_DRAFT":       1,
	"ASSET_STATUS_ATTESTED":    2,
	"ASSET_STATUS_ACTIVE":      3,
	"ASSET_STATUS_SETTLED":     4,
}

func (x AssetStatus) String() string {
	return proto.EnumName(AssetStatus_name, int32(x))
}

func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8cef1fded3955ae, []int{0}
}

// AssetRecord is the registry entry for one RWA asset.
type AssetRecord struct {
	AssetId        string      `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Issuer         string      `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Name           string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status         AssetStatus `protobuf:"varint,5,opt,name=status,proto3,enum=vertix.rwa.v1.AssetStatus" json:"status,omitempty"`
	OraclePair     string      `protobuf:"bytes,6,opt,name=oracle_pair,json=oraclePair,proto3" json:"oracle_pair,omitempty"`
	Denom          string      `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
	Bond           string      `protobuf:"bytes,8,opt,name=bond,proto3" json:"bond,omitempty"`
	NotionalMinted string      `protobuf:"bytes,9,opt,name=notional_minted,json=notionalMinted,proto3" json:"notional_minted,omitempty"`
	AllowAll       bool        `protobuf:"varint,10,opt,name=allow_all,json=allowAll,proto3" json:"allow_all,omitempty"`
	AttestedPrice  string      `protobuf:"bytes,11,opt,name=attested_price,json=attestedPrice,proto3" json:"attested_price,omitempty"`
	AttestedAt     time.Time   `protobuf:"bytes,12,opt,name=attested_at,json=attestedAt,proto3,stdtime" json:"attested_at"`
	CreatedAt      time.Time   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	SettledAt      time.Time   `protobuf:"bytes,14,opt,name=settled_at,json=settledAt,proto3,stdtime" json:"settled_at"`
}

func (m *AssetRecord) Reset()         { *m = AssetRecord{} }
func (m *AssetRecord) String() string { return proto.CompactTextString(m) }
func (*AssetRecord) ProtoMessage()    {}
func (*AssetRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8cef1fded3955ae, []int{0}
}
func (m *AssetRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetRecord.Merge(m, src)
}
func (m *AssetRecord) XXX_Size() int {
	return m.Size()
}
func (m *AssetRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AssetRecord proto.InternalMessageInfo

func (m *AssetRecord) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *AssetRecord) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *AssetRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssetRecord) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AssetRecord) GetStatus() AssetStatus {
	if m != nil {
		return m.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (m *AssetRecord) GetOraclePair() string {
	if m != nil {
		return m.OraclePair
	}
	return ""
}

func (m *AssetRecord) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *AssetRecord) GetBond() string {
	if m != nil {
		return m.Bond
	}
	return ""
}

func (m *AssetRecord) GetNotionalMinted() string {
	if m != nil {
		return m.NotionalMinted
	}
	return ""
}

func (m *AssetRecord) GetAllowAll() bool {
	if m != nil {
		return m.AllowAll
	}
	return false
}

func (m *AssetRecord) GetAttestedPrice() string {
	if m != nil {
		return m.AttestedPrice
	}
	return ""
}

func (m *AssetRecord) GetAttestedAt() time.Time {
	if m != nil {
		return m.AttestedAt
	}
	return time.Time{}
}

func (m *AssetRecord) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *AssetRecord) GetSettledAt() time.Time {
	if m != nil {
		return m.SettledAt
	}
	return time.Time{}
}

// RWAParams defines module governance parameters.
type RWAParams struct {
	MinIssuerBond string `protobuf:"bytes,1,opt,name=min_issuer_bond,json=minIssuerBond,proto3" json:"min_issuer_bond,omitempty"`
	MintFeeRate   string `protobuf:"bytes,2,opt,name=mint_fee_rate,json=mintFeeRate,proto3" json:"mint_fee_rate,omitempty"`
	SettleFeeRate string `protobuf:"bytes,3,opt,name=settle_fee_rate,json=settleFeeRate,proto3" json:"settle_fee_rate,omitempty"`
}

func (m *RWAParams) Reset()         { *m = RWAParams{} }
func (m *RWAParams) String() string { return proto.CompactTextString(m) }
func (*RWAParams) ProtoMessage()    {}
func (*RWAParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8cef1fded3955ae, []int{1}
}
func (m *RWAParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RWAParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RWAParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RWAParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWAParams.Merge(m, src)
}
func (m *RWAParams) XXX_Size() int {
	return m.Size()
}
func (m *RWAParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RWAParams.DiscardUnknown(m)
}

var xxx_messageInfo_RWAParams proto.InternalMessageInfo

func (m *RWAParams) GetMinIssuerBond() string {
	if m != nil {
		return m.MinIssuerBond
	}
	return ""
}

func (m *RWAParams) GetMintFeeRate() string {
	if m != nil {
		return m.MintFeeRate
	}
	return ""
}

func (m *RWAParams) GetSettleFeeRate() string {
	if m != nil {
		return m.SettleFeeRate
	}
	return ""
}

func init() {
	proto.RegisterEnum("vertix.rwa.v1.AssetStatus", AssetStatus_name, AssetStatus_value)
	proto.RegisterType((*AssetRecord)(nil), "vertix.rwa.v1.AssetRecord")
	proto.RegisterType((*RWAParams)(nil), "vertix.rwa.v1.RWAParams")
}

func init() { proto.RegisterFile("vertix/rwa/v1/types.proto", fileDescriptor_f8cef1fded3955ae) }

var fileDescriptor_f8cef1fded3955ae = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x6f, 0xd3, 0x3a,
	0x18, 0x6d, 0xb6, 0xae, 0x6b, 0xdd, 0xdb, 0xae, 0xf2, 0xed, 0xbd, 0xd7, 0xed, 0x45, 0x6d, 0xb5,
	0xa7, 0x0a, 0xb1, 0x84, 0x15, 0x01, 0xcf, 0xe9, 0x9a, 0x4a, 0x95, 0x00, 0x55, 0x49, 0x06, 0x12,
	0x2f, 0x91, 0x9b, 0x78, 0xc5, 0x22, 0x89, 0x2b, 0xdb, 0x5d, 0xe1, 0x5f, 0x8c, 0x5f, 0xc2, 0xcb,
	0x7e, 0xc4, 0x1e, 0xa7, 0x3d, 0xf1, 0x04, 0x68, 0xfb, 0x1d, 0x48, 0x28, 0x76, 0x0a, 0x14, 0xf6,
	0xb2, 0xb7, 0x7c, 0xe7, 0x9c, 0xef, 0xe4, 0xb3, 0x8f, 0x6d, 0xd0, 0x3a, 0x25, 0x5c, 0xd2, 0x77,
	0x16, 0x5f, 0x61, 0xeb, 0xf4, 0xd0, 0x92, 0xef, 0x17, 0x44, 0x98, 0x0b, 0xce, 0x24, 0x83, 0x35,
	0x4d, 0x99, 0x7c, 0x85, 0xcd, 0xd3, 0xc3, 0x76, 0x2b, 0x64, 0x22, 0x61, 0x22, 0x50, 0xa4, 0xa5,
	0x0b, 0xad, 0x6c, 0x37, 0xe7, 0x6c, 0xce, 0x34, 0x9e, 0x7d, 0xe5, 0x68, 0x77, 0xce, 0xd8, 0x3c,
	0x26, 0x96, 0xaa, 0x66, 0xcb, 0x13, 0x4b, 0xd2, 0x84, 0x08, 0x89, 0x93, 0x85, 0x16, 0xec, 0x7f,
	0x2b, 0x82, 0xaa, 0x2d, 0x04, 0x91, 0x2e, 0x09, 0x19, 0x8f, 0x60, 0x0b, 0x94, 0x71, 0x56, 0x06,
	0x34, 0x42, 0x46, 0xcf, 0xe8, 0x57, 0xdc, 0x5d, 0x55, 0x4f, 0x22, 0xf8, 0x10, 0x94, 0xa8, 0x10,
	0x4b, 0xc2, 0xd1, 0x56, 0x46, 0x0c, 0xd1, 0xd5, 0xf9, 0x41, 0x33, 0x9f, 0xc1, 0x8e, 0x22, 0x4e,
	0x84, 0xf0, 0x24, 0xa7, 0xe9, 0xdc, 0xcd, 0x75, 0x10, 0x82, 0x62, 0x8a, 0x13, 0x82, 0xb6, 0x95,
	0x91, 0xfa, 0x86, 0x3d, 0x50, 0x8d, 0x88, 0x08, 0x39, 0x5d, 0x48, 0xca, 0x52, 0x54, 0x54, 0xd4,
	0xaf, 0x10, 0x1c, 0x80, 0x92, 0x90, 0x58, 0x2e, 0x05, 0xda, 0xe9, 0x19, 0xfd, 0xfa, 0xa0, 0x6d,
	0x6e, 0x6c, 0x82, 0xa9, 0xc6, 0xf5, 0x94, 0xc2, 0xcd, 0x95, 0xb0, 0x0b, 0xaa, 0x8c, 0xe3, 0x30,
	0x26, 0xc1, 0x02, 0x53, 0x8e, 0x4a, 0xca, 0x15, 0x68, 0x68, 0x8a, 0x29, 0x87, 0x4d, 0xb0, 0x13,
	0x91, 0x94, 0x25, 0x68, 0x57, 0x51, 0xba, 0x80, 0xfb, 0xa0, 0x38, 0x63, 0x69, 0x84, 0xca, 0x6a,
	0x41, 0xf5, 0xab, 0xf3, 0x03, 0x90, 0x2f, 0x68, 0x92, 0x4a, 0x57, 0x71, 0xf0, 0x29, 0xd8, 0x4b,
	0x59, 0x36, 0x18, 0x8e, 0x83, 0x84, 0xa6, 0x92, 0x44, 0xa8, 0x72, 0xab, 0xbc, 0xbe, 0x96, 0x3d,
	0x57, 0x2a, 0xf8, 0x3f, 0xa8, 0xe0, 0x38, 0x66, 0xab, 0x00, 0xc7, 0x31, 0x02, 0x3d, 0xa3, 0x5f,
	0x76, 0xcb, 0x0a, 0xb0, 0xe3, 0x18, 0x3e, 0x06, 0x75, 0x2c, 0x25, 0x11, 0x92, 0x44, 0xc1, 0x82,
	0xd3, 0x90, 0xa0, 0xea, 0x1f, 0xa6, 0x23, 0x12, 0xba, 0xb5, 0xb5, 0x6a, 0x9a, 0x89, 0xa0, 0x03,
	0xaa, 0x3f, 0xda, 0xb0, 0x44, 0x7f, 0xf5, 0x8c, 0x7e, 0x75, 0xd0, 0x36, 0x75, 0xca, 0xe6, 0x3a,
	0x65, 0xd3, 0x5f, 0xa7, 0x3c, 0x2c, 0x5f, 0x7c, 0xee, 0x16, 0xce, 0xbe, 0x74, 0x0d, 0x17, 0xac,
	0x1b, 0x6d, 0x09, 0x8f, 0x00, 0x08, 0x39, 0xc1, 0xb9, 0x4b, 0xed, 0x0e, 0x2e, 0x95, 0xbc, 0x4f,
	0x9b, 0x08, 0x22, 0x65, 0xac, 0x4d, 0xea, 0x77, 0x31, 0xc9, 0xfb, 0x6c, 0xb9, 0xff, 0xd1, 0x00,
	0x15, 0xf7, 0x95, 0x3d, 0xc5, 0x1c, 0x27, 0x02, 0x3e, 0x01, 0x7b, 0x09, 0x4d, 0x03, 0x7d, 0x7c,
	0x02, 0x15, 0x8d, 0x71, 0xeb, 0x5e, 0xd7, 0x12, 0x9a, 0x4e, 0x94, 0x6a, 0x98, 0x65, 0x34, 0x00,
	0x19, 0x20, 0x83, 0x13, 0x42, 0x02, 0x8e, 0x25, 0xc9, 0x4f, 0xe8, 0xef, 0x9b, 0x59, 0xcd, 0x44,
	0x63, 0x42, 0x5c, 0x2c, 0x49, 0xf6, 0x2f, 0x3d, 0xc6, 0xcf, 0xae, 0xed, 0xdb, 0x23, 0xd0, 0xb2,
	0xbc, 0xef, 0xfe, 0x07, 0x23, 0xbf, 0x31, 0xfa, 0x08, 0xc2, 0x7b, 0x00, 0xd9, 0x9e, 0xe7, 0xf8,
	0x81, 0xe7, 0xdb, 0xfe, 0xb1, 0x17, 0x1c, 0xbf, 0xf0, 0xa6, 0xce, 0xd1, 0x64, 0x3c, 0x71, 0x46,
	0x8d, 0x02, 0xfc, 0x17, 0xc0, 0x0d, 0x76, 0xe4, 0xda, 0x63, 0xbf, 0x61, 0xc0, 0x16, 0xf8, 0x67,
	0x03, 0xb7, 0x7d, 0xdf, 0xf1, 0x7c, 0x67, 0xd4, 0xd8, 0x82, 0xff, 0x81, 0xbf, 0x37, 0xa9, 0x23,
	0x7f, 0xf2, 0xd2, 0x69, 0x6c, 0x43, 0x04, 0x9a, 0x1b, 0x84, 0xe7, 0xf8, 0xfe, 0x33, 0x67, 0xd4,
	0x28, 0x0e, 0xc7, 0x17, 0xd7, 0x1d, 0xe3, 0xf2, 0xba, 0x63, 0x7c, 0xbd, 0xee, 0x18, 0x67, 0x37,
	0x9d, 0xc2, 0xe5, 0x4d, 0xa7, 0xf0, 0xe9, 0xa6, 0x53, 0x78, 0xfd, 0x60, 0x4e, 0xe5, 0x9b, 0xe5,
	0xcc, 0x0c, 0x59, 0x62, 0xe9, 0x6b, 0x74, 0x90, 0x12, 0xb9, 0x62, 0xfc, 0x6d, 0x5e, 0x5a, 0xfa,
	0xdd, 0x51, 0x8f, 0xce, 0xac, 0xa4, 0x62, 0x7b, 0xf4, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x39,
	0x86, 0x40, 0x92, 0x04, 0x00, 0x00,
}

func (m *AssetRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.SettledAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SettledAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTypes(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x72
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x6a
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.AttestedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AttestedAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTypes(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x62
	if len(m.AttestedPrice) > 0 {
		i -= len(m.AttestedPrice)
		copy(dAtA[i:], m.AttestedPrice)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AttestedPrice)))
		i--
		dAtA[i] = 0x5a
	}
	if m.AllowAll {
		i--
		if m.AllowAll {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if len(m.NotionalMinted) > 0 {
		i -= len(m.NotionalMinted)
		copy(dAtA[i:], m.NotionalMinted)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.NotionalMinted)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Bond) > 0 {
		i -= len(m.Bond)
		copy(dAtA[i:], m.Bond)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Bond)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.OraclePair) > 0 {
		i -= len(m.OraclePair)
		copy(dAtA[i:], m.OraclePair)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OraclePair)))
		i--
		dAtA[i] = 0x32
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RWAParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RWAParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RWAParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SettleFeeRate) > 0 {
		i -= len(m.SettleFeeRate)
		copy(dAtA[i:], m.SettleFeeRate)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SettleFeeRate)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MintFeeRate) > 0 {
		i -= len(m.MintFeeRate)
		copy(dAtA[i:], m.MintFeeRate)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MintFeeRate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MinIssuerBond) > 0 {
		i -= len(m.MinIssuerBond)
		copy(dAtA[i:], m.MinIssuerBond)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MinIssuerBond)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AssetRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.OraclePair)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Bond)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.NotionalMinted)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AllowAll {
		n += 2
	}
	l = len(m.AttestedPrice)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AttestedAt)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SettledAt)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *RWAParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MinIssuerBond)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.MintFeeRate)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SettleFeeRate)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AssetRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= AssetStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OraclePair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bond = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotionalMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NotionalMinted = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowAll", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowAll = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestedPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestedPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.AttestedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettledAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.SettledAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RWAParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RWAParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RWAParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinIssuerBond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinIssuerBond = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintFeeRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettleFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettleFeeRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
