#!/usr/bin/env bash
# One-time generator for devnet key material. Run once; commit the outputs.
# Produces infra/devnet/mnemonics.env and fixed node/consensus keys per validator.
set -euo pipefail
cd "$(dirname "$0")/../.."
. scripts/devnet/lib.sh
require docker

OUT_KEYS="infra/devnet/keys"
MNEMO="infra/devnet/mnemonics.env"
NAMES=(val1 val2 val3 feeder1 feeder2 feeder3 faucet relayer testuser)

[ -f "$MNEMO" ] && die "$MNEMO already exists; refusing to overwrite committed keys"

log "Generating mnemonics for: ${NAMES[*]}"
{
  echo "# infra/devnet/mnemonics.env — FIXED DEVNET-ONLY KEY MATERIAL."
  echo "# !!! NEVER fund these on a real network. Generated by scripts/devnet/gen-keys.sh. !!!"
} > "$MNEMO"

for n in "${NAMES[@]}"; do
  m=$(docker run --rm vertix:devnet vertixd keys mnemonic)
  key="MNEMONIC_$(echo "$n" | tr '[:lower:]' '[:upper:]')"
  echo "${key}=\"${m}\"" >> "$MNEMO"
done

log "Generating fixed node_key.json + priv_validator_key.json per validator"
for i in 1 2 3; do
  d="$OUT_KEYS/validator$i"; mkdir -p "$d"
  tmp=$(mktemp -d)
  docker run --rm -v "$tmp:/home/.vertix" vertix:devnet \
    vertixd init "val$i" --chain-id vertix-devnet-1 --default-denom uvtx --home /home/.vertix >/dev/null 2>&1
  cp "$tmp/config/node_key.json" "$d/node_key.json"
  cp "$tmp/config/priv_validator_key.json" "$d/priv_validator_key.json"
  rm -rf "$tmp"
done
log "Done. Review $MNEMO and $OUT_KEYS, then commit."
