// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vertix/oracle/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OracleFeed is a single validator price vote for a pair at a block height.
type OracleFeed struct {
	Validator   string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Pair        string `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Price       string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	BlockHeight int64  `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *OracleFeed) Reset()         { *m = OracleFeed{} }
func (m *OracleFeed) String() string { return proto.CompactTextString(m) }
func (*OracleFeed) ProtoMessage()    {}
func (*OracleFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_f125b50d9beef35a, []int{0}
}
func (m *OracleFeed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleFeed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleFeed.Merge(m, src)
}
func (m *OracleFeed) XXX_Size() int {
	return m.Size()
}
func (m *OracleFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleFeed.DiscardUnknown(m)
}

var xxx_messageInfo_OracleFeed proto.InternalMessageInfo

func (m *OracleFeed) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *OracleFeed) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *OracleFeed) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OracleFeed) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// AggregatedPrice is the stake-weighted median price for a pair.
type AggregatedPrice struct {
	Pair        string    `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price       string    `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	BlockHeight int64     `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTime   time.Time `protobuf:"bytes,4,opt,name=block_time,json=blockTime,proto3,stdtime" json:"block_time"`
}

func (m *AggregatedPrice) Reset()         { *m = AggregatedPrice{} }
func (m *AggregatedPrice) String() string { return proto.CompactTextString(m) }
func (*AggregatedPrice) ProtoMessage()    {}
func (*AggregatedPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_f125b50d9beef35a, []int{1}
}
func (m *AggregatedPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AggregatedPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AggregatedPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AggregatedPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedPrice.Merge(m, src)
}
func (m *AggregatedPrice) XXX_Size() int {
	return m.Size()
}
func (m *AggregatedPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedPrice.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedPrice proto.InternalMessageInfo

func (m *AggregatedPrice) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *AggregatedPrice) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *AggregatedPrice) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *AggregatedPrice) GetBlockTime() time.Time {
	if m != nil {
		return m.BlockTime
	}
	return time.Time{}
}

// TWAPEntry is one sample in the time-weighted average price ring buffer.
type TWAPEntry struct {
	Pair      string    `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price     string    `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	BlockTime time.Time `protobuf:"bytes,3,opt,name=block_time,json=blockTime,proto3,stdtime" json:"block_time"`
}

func (m *TWAPEntry) Reset()         { *m = TWAPEntry{} }
func (m *TWAPEntry) String() string { return proto.CompactTextString(m) }
func (*TWAPEntry) ProtoMessage()    {}
func (*TWAPEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f125b50d9beef35a, []int{2}
}
func (m *TWAPEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TWAPEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TWAPEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TWAPEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TWAPEntry.Merge(m, src)
}
func (m *TWAPEntry) XXX_Size() int {
	return m.Size()
}
func (m *TWAPEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TWAPEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TWAPEntry proto.InternalMessageInfo

func (m *TWAPEntry) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *TWAPEntry) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TWAPEntry) GetBlockTime() time.Time {
	if m != nil {
		return m.BlockTime
	}
	return time.Time{}
}

// OracleParams defines module governance parameters.
type OracleParams struct {
	VoteWindow       int64    `protobuf:"varint,1,opt,name=vote_window,json=voteWindow,proto3" json:"vote_window,omitempty"`
	MissThreshold    string   `protobuf:"bytes,2,opt,name=miss_threshold,json=missThreshold,proto3" json:"miss_threshold,omitempty"`
	MissSlashRate    string   `protobuf:"bytes,3,opt,name=miss_slash_rate,json=missSlashRate,proto3" json:"miss_slash_rate,omitempty"`
	OutlierSlashRate string   `protobuf:"bytes,4,opt,name=outlier_slash_rate,json=outlierSlashRate,proto3" json:"outlier_slash_rate,omitempty"`
	OutlierThreshold string   `protobuf:"bytes,5,opt,name=outlier_threshold,json=outlierThreshold,proto3" json:"outlier_threshold,omitempty"`
	MissWindowSize   int64    `protobuf:"varint,6,opt,name=miss_window_size,json=missWindowSize,proto3" json:"miss_window_size,omitempty"`
	QuorumFraction   string   `protobuf:"bytes,7,opt,name=quorum_fraction,json=quorumFraction,proto3" json:"quorum_fraction,omitempty"`
	MaxPriceAge      int64    `protobuf:"varint,8,opt,name=max_price_age,json=maxPriceAge,proto3" json:"max_price_age,omitempty"`
	AcceptList       []string `protobuf:"bytes,9,rep,name=accept_list,json=acceptList,proto3" json:"accept_list,omitempty"`
}

func (m *OracleParams) Reset()         { *m = OracleParams{} }
func (m *OracleParams) String() string { return proto.CompactTextString(m) }
func (*OracleParams) ProtoMessage()    {}
func (*OracleParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f125b50d9beef35a, []int{3}
}
func (m *OracleParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleParams.Merge(m, src)
}
func (m *OracleParams) XXX_Size() int {
	return m.Size()
}
func (m *OracleParams) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleParams.DiscardUnknown(m)
}

var xxx_messageInfo_OracleParams proto.InternalMessageInfo

func (m *OracleParams) GetVoteWindow() int64 {
	if m != nil {
		return m.VoteWindow
	}
	return 0
}

func (m *OracleParams) GetMissThreshold() string {
	if m != nil {
		return m.MissThreshold
	}
	return ""
}

func (m *OracleParams) GetMissSlashRate() string {
	if m != nil {
		return m.MissSlashRate
	}
	return ""
}

func (m *OracleParams) GetOutlierSlashRate() string {
	if m != nil {
		return m.OutlierSlashRate
	}
	return ""
}

func (m *OracleParams) GetOutlierThreshold() string {
	if m != nil {
		return m.OutlierThreshold
	}
	return ""
}

func (m *OracleParams) GetMissWindowSize() int64 {
	if m != nil {
		return m.MissWindowSize
	}
	return 0
}

func (m *OracleParams) GetQuorumFraction() string {
	if m != nil {
		return m.QuorumFraction
	}
	return ""
}

func (m *OracleParams) GetMaxPriceAge() int64 {
	if m != nil {
		return m.MaxPriceAge
	}
	return 0
}

func (m *OracleParams) GetAcceptList() []string {
	if m != nil {
		return m.AcceptList
	}
	return nil
}

func init() {
	proto.RegisterType((*OracleFeed)(nil), "vertix.oracle.v1.OracleFeed")
	proto.RegisterType((*AggregatedPrice)(nil), "vertix.oracle.v1.AggregatedPrice")
	proto.RegisterType((*TWAPEntry)(nil), "vertix.oracle.v1.TWAPEntry")
	proto.RegisterType((*OracleParams)(nil), "vertix.oracle.v1.OracleParams")
}

func init() { proto.RegisterFile("vertix/oracle/v1/types.proto", fileDescriptor_f125b50d9beef35a) }

var fileDescriptor_f125b50d9beef35a = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x6e, 0x96, 0x6d, 0x2c, 0xde, 0x57, 0xb1, 0x76, 0x08, 0x15, 0x4a, 0x4b, 0xc5, 0xa1, 0x97,
	0x26, 0x1a, 0x88, 0x71, 0x80, 0x4b, 0x0b, 0x4c, 0x20, 0x21, 0x51, 0xa5, 0x95, 0x26, 0x71, 0x89,
	0xdc, 0xc4, 0x73, 0xac, 0x25, 0x75, 0xb0, 0xdd, 0x8f, 0xed, 0x27, 0x70, 0xda, 0x5f, 0xe0, 0x37,
	0xb0, 0x3f, 0xc0, 0x6d, 0xc7, 0x69, 0x27, 0x4e, 0x80, 0xda, 0x3f, 0x82, 0x62, 0xa7, 0x14, 0x44,
	0x87, 0x04, 0xdc, 0xec, 0xf7, 0x79, 0x9e, 0xf7, 0x7d, 0xf4, 0xbc, 0x96, 0xc1, 0xdd, 0x11, 0xe6,
	0x92, 0x4e, 0x3c, 0xc6, 0x51, 0x98, 0x60, 0x6f, 0xb4, 0xef, 0xc9, 0xd3, 0x0c, 0x0b, 0x37, 0xe3,
	0x4c, 0x32, 0x58, 0xd6, 0xa8, 0xab, 0x51, 0x77, 0xb4, 0x5f, 0xd9, 0x23, 0x8c, 0x30, 0x05, 0x7a,
	0xf9, 0x49, 0xf3, 0x2a, 0x77, 0x42, 0x26, 0x52, 0x26, 0x02, 0x0d, 0xe8, 0x4b, 0x01, 0x55, 0x09,
	0x63, 0x24, 0xc1, 0x9e, 0xba, 0xf5, 0x87, 0xc7, 0x9e, 0xa4, 0x29, 0x16, 0x12, 0xa5, 0x99, 0x26,
	0xd4, 0x3f, 0x18, 0x00, 0xbc, 0x51, 0xfd, 0x0f, 0x31, 0x8e, 0xe0, 0x01, 0xb0, 0x46, 0x28, 0xa1,
	0x11, 0x92, 0x8c, 0xdb, 0x46, 0xcd, 0x68, 0x58, 0x6d, 0xfb, 0xfa, 0xa2, 0xb9, 0x57, 0x34, 0x6d,
	0x45, 0x11, 0xc7, 0x42, 0x74, 0x25, 0xa7, 0x03, 0xe2, 0x2f, 0xa8, 0x10, 0x82, 0xd5, 0x0c, 0x51,
	0x6e, 0xaf, 0xe4, 0x12, 0x5f, 0x9d, 0xe1, 0x7d, 0xb0, 0x96, 0x71, 0x1a, 0x62, 0xdb, 0x54, 0x7d,
	0x76, 0xae, 0x2f, 0x9a, 0xa0, 0xe8, 0xf3, 0x1c, 0x87, 0xbe, 0x06, 0xe1, 0x3d, 0xb0, 0xd5, 0x4f,
	0x58, 0x78, 0x12, 0xc4, 0x98, 0x92, 0x58, 0xda, 0xab, 0x35, 0xa3, 0x61, 0xfa, 0x9b, 0xaa, 0xf6,
	0x52, 0x95, 0xea, 0x1f, 0x0d, 0xb0, 0xdb, 0x22, 0x84, 0x63, 0x82, 0x24, 0x8e, 0x3a, 0x4a, 0x36,
	0x1f, 0x68, 0x2c, 0x1b, 0xb8, 0xf2, 0x37, 0x03, 0xcd, 0xdf, 0x06, 0xc2, 0x67, 0x00, 0x68, 0x4a,
	0x9e, 0x96, 0x72, 0xb4, 0xf9, 0xa0, 0xe2, 0xea, 0x28, 0xdd, 0x79, 0x94, 0x6e, 0x6f, 0x1e, 0x65,
	0x7b, 0xe3, 0xf2, 0x4b, 0xb5, 0x74, 0xfe, 0xb5, 0x6a, 0xf8, 0x96, 0xd2, 0xe5, 0x48, 0xfd, 0xbd,
	0x01, 0xac, 0xde, 0x51, 0xab, 0xf3, 0x62, 0x20, 0xf9, 0xe9, 0x7f, 0xf8, 0xfd, 0xd5, 0x8c, 0xf9,
	0x6f, 0x66, 0x3e, 0x99, 0x60, 0x4b, 0xaf, 0xb9, 0x83, 0x38, 0x4a, 0x05, 0xac, 0x82, 0xcd, 0x11,
	0x93, 0x38, 0x18, 0xd3, 0x41, 0xc4, 0xc6, 0xca, 0x96, 0xe9, 0x83, 0xbc, 0x74, 0xa4, 0x2a, 0xf0,
	0x11, 0xd8, 0x49, 0xa9, 0x10, 0x81, 0x8c, 0x39, 0x16, 0x31, 0x4b, 0xa2, 0x1b, 0x5c, 0x6e, 0xe7,
	0xac, 0xde, 0x9c, 0x04, 0x0f, 0xc0, 0xae, 0x92, 0x89, 0x04, 0x89, 0x38, 0xe0, 0x48, 0xde, 0xb4,
	0x7e, 0xa5, 0xeb, 0xe6, 0x2c, 0x1f, 0x49, 0x0c, 0x9f, 0x02, 0xc8, 0x86, 0x32, 0xa1, 0x98, 0xff,
	0x2c, 0x5d, 0x5d, 0x2a, 0x2d, 0x17, 0xcc, 0x85, 0xfa, 0x09, 0xb8, 0x3d, 0x57, 0x2f, 0xfc, 0xae,
	0xfd, 0x51, 0xbc, 0xb0, 0xdc, 0x00, 0x65, 0x65, 0x59, 0x47, 0x11, 0x08, 0x7a, 0x86, 0xed, 0x75,
	0x95, 0x87, 0x4a, 0x40, 0xe7, 0xd1, 0xa5, 0x67, 0x18, 0x3e, 0x06, 0xbb, 0xef, 0x86, 0x8c, 0x0f,
	0xd3, 0xe0, 0x98, 0xa3, 0x50, 0x52, 0x36, 0xb0, 0x6f, 0x2d, 0x1d, 0xb2, 0xa3, 0x69, 0x87, 0x05,
	0x0b, 0xd6, 0xc1, 0x76, 0x8a, 0x26, 0x81, 0x5a, 0x68, 0x80, 0x08, 0xb6, 0x37, 0xf4, 0xa3, 0x4b,
	0xd1, 0x44, 0x3d, 0xe7, 0x16, 0xc1, 0xf9, 0x46, 0x50, 0x18, 0xe2, 0x4c, 0x06, 0x09, 0x15, 0xd2,
	0xb6, 0x6a, 0x66, 0xc3, 0xf2, 0x81, 0x2e, 0xbd, 0xa6, 0x42, 0xb6, 0x5f, 0x5d, 0x4e, 0x1d, 0xe3,
	0x6a, 0xea, 0x18, 0xdf, 0xa6, 0x8e, 0x71, 0x3e, 0x73, 0x4a, 0x57, 0x33, 0xa7, 0xf4, 0x79, 0xe6,
	0x94, 0xde, 0x7a, 0x84, 0xca, 0x78, 0xd8, 0x77, 0x43, 0x96, 0x7a, 0xfa, 0xcf, 0x68, 0x0e, 0xb0,
	0x1c, 0x33, 0x7e, 0x52, 0x5c, 0xbd, 0x1f, 0x5f, 0x8c, 0xfa, 0x5f, 0xfa, 0xeb, 0xea, 0xdd, 0x3c,
	0xfc, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x83, 0x69, 0x0c, 0x11, 0x80, 0x04, 0x00, 0x00,
}

func (m *OracleFeed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleFeed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleFeed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AggregatedPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AggregatedPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregatedPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.BlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.BlockTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTypes(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	if m.BlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TWAPEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TWAPEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TWAPEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.BlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.BlockTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AcceptList) > 0 {
		for iNdEx := len(m.AcceptList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AcceptList[iNdEx])
			copy(dAtA[i:], m.AcceptList[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.AcceptList[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.MaxPriceAge != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxPriceAge))
		i--
		dAtA[i] = 0x40
	}
	if len(m.QuorumFraction) > 0 {
		i -= len(m.QuorumFraction)
		copy(dAtA[i:], m.QuorumFraction)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.QuorumFraction)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MissWindowSize != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MissWindowSize))
		i--
		dAtA[i] = 0x30
	}
	if len(m.OutlierThreshold) > 0 {
		i -= len(m.OutlierThreshold)
		copy(dAtA[i:], m.OutlierThreshold)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutlierThreshold)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OutlierSlashRate) > 0 {
		i -= len(m.OutlierSlashRate)
		copy(dAtA[i:], m.OutlierSlashRate)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutlierSlashRate)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MissSlashRate) > 0 {
		i -= len(m.MissSlashRate)
		copy(dAtA[i:], m.MissSlashRate)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MissSlashRate)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MissThreshold) > 0 {
		i -= len(m.MissThreshold)
		copy(dAtA[i:], m.MissThreshold)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MissThreshold)))
		i--
		dAtA[i] = 0x12
	}
	if m.VoteWindow != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VoteWindow))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OracleFeed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.BlockHeight))
	}
	return n
}

func (m *AggregatedPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.BlockHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.BlockTime)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *TWAPEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.BlockTime)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *OracleParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VoteWindow != 0 {
		n += 1 + sovTypes(uint64(m.VoteWindow))
	}
	l = len(m.MissThreshold)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.MissSlashRate)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OutlierSlashRate)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OutlierThreshold)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MissWindowSize != 0 {
		n += 1 + sovTypes(uint64(m.MissWindowSize))
	}
	l = len(m.QuorumFraction)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MaxPriceAge != 0 {
		n += 1 + sovTypes(uint64(m.MaxPriceAge))
	}
	if len(m.AcceptList) > 0 {
		for _, s := range m.AcceptList {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OracleFeed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleFeed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleFeed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AggregatedPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AggregatedPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AggregatedPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.BlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TWAPEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TWAPEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TWAPEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.BlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteWindow", wireType)
			}
			m.VoteWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MissThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissSlashRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MissSlashRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutlierSlashRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutlierSlashRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutlierThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutlierThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissWindowSize", wireType)
			}
			m.MissWindowSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissWindowSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuorumFraction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceAge", wireType)
			}
			m.MaxPriceAge = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPriceAge |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptList = append(m.AcceptList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
