// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rwav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	RegisterAsset(ctx context.Context, in *MsgRegisterAsset, opts ...grpc.CallOption) (*MsgRegisterAssetResponse, error)
	AttestAsset(ctx context.Context, in *MsgAttestAsset, opts ...grpc.CallOption) (*MsgAttestAssetResponse, error)
	MintRWA(ctx context.Context, in *MsgMintRWA, opts ...grpc.CallOption) (*MsgMintRWAResponse, error)
	TransferRWA(ctx context.Context, in *MsgTransferRWA, opts ...grpc.CallOption) (*MsgTransferRWAResponse, error)
	SettleRWA(ctx context.Context, in *MsgSettleRWA, opts ...grpc.CallOption) (*MsgSettleRWAResponse, error)
	UpdateRestrictions(ctx context.Context, in *MsgUpdateRestrictions, opts ...grpc.CallOption) (*MsgUpdateRestrictionsResponse, error)
	SlashBond(ctx context.Context, in *MsgSlashBond, opts ...grpc.CallOption) (*MsgSlashBondResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterAsset(ctx context.Context, in *MsgRegisterAsset, opts ...grpc.CallOption) (*MsgRegisterAssetResponse, error) {
	out := new(MsgRegisterAssetResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/RegisterAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AttestAsset(ctx context.Context, in *MsgAttestAsset, opts ...grpc.CallOption) (*MsgAttestAssetResponse, error) {
	out := new(MsgAttestAssetResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/AttestAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintRWA(ctx context.Context, in *MsgMintRWA, opts ...grpc.CallOption) (*MsgMintRWAResponse, error) {
	out := new(MsgMintRWAResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/MintRWA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferRWA(ctx context.Context, in *MsgTransferRWA, opts ...grpc.CallOption) (*MsgTransferRWAResponse, error) {
	out := new(MsgTransferRWAResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/TransferRWA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SettleRWA(ctx context.Context, in *MsgSettleRWA, opts ...grpc.CallOption) (*MsgSettleRWAResponse, error) {
	out := new(MsgSettleRWAResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/SettleRWA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateRestrictions(ctx context.Context, in *MsgUpdateRestrictions, opts ...grpc.CallOption) (*MsgUpdateRestrictionsResponse, error) {
	out := new(MsgUpdateRestrictionsResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/UpdateRestrictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SlashBond(ctx context.Context, in *MsgSlashBond, opts ...grpc.CallOption) (*MsgSlashBondResponse, error) {
	out := new(MsgSlashBondResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/SlashBond", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/vertix.rwa.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	RegisterAsset(context.Context, *MsgRegisterAsset) (*MsgRegisterAssetResponse, error)
	AttestAsset(context.Context, *MsgAttestAsset) (*MsgAttestAssetResponse, error)
	MintRWA(context.Context, *MsgMintRWA) (*MsgMintRWAResponse, error)
	TransferRWA(context.Context, *MsgTransferRWA) (*MsgTransferRWAResponse, error)
	SettleRWA(context.Context, *MsgSettleRWA) (*MsgSettleRWAResponse, error)
	UpdateRestrictions(context.Context, *MsgUpdateRestrictions) (*MsgUpdateRestrictionsResponse, error)
	SlashBond(context.Context, *MsgSlashBond) (*MsgSlashBondResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) RegisterAsset(context.Context, *MsgRegisterAsset) (*MsgRegisterAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAsset not implemented")
}
func (UnimplementedMsgServer) AttestAsset(context.Context, *MsgAttestAsset) (*MsgAttestAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestAsset not implemented")
}
func (UnimplementedMsgServer) MintRWA(context.Context, *MsgMintRWA) (*MsgMintRWAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintRWA not implemented")
}
func (UnimplementedMsgServer) TransferRWA(context.Context, *MsgTransferRWA) (*MsgTransferRWAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferRWA not implemented")
}
func (UnimplementedMsgServer) SettleRWA(context.Context, *MsgSettleRWA) (*MsgSettleRWAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleRWA not implemented")
}
func (UnimplementedMsgServer) UpdateRestrictions(context.Context, *MsgUpdateRestrictions) (*MsgUpdateRestrictionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestrictions not implemented")
}
func (UnimplementedMsgServer) SlashBond(context.Context, *MsgSlashBond) (*MsgSlashBondResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SlashBond not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegisterAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/RegisterAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterAsset(ctx, req.(*MsgRegisterAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AttestAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAttestAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AttestAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/AttestAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AttestAsset(ctx, req.(*MsgAttestAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintRWA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintRWA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintRWA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/MintRWA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintRWA(ctx, req.(*MsgMintRWA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferRWA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferRWA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferRWA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/TransferRWA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferRWA(ctx, req.(*MsgTransferRWA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SettleRWA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSettleRWA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SettleRWA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/SettleRWA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SettleRWA(ctx, req.(*MsgSettleRWA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateRestrictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateRestrictions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateRestrictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/UpdateRestrictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateRestrictions(ctx, req.(*MsgUpdateRestrictions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SlashBond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSlashBond)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SlashBond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/SlashBond",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SlashBond(ctx, req.(*MsgSlashBond))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vertix.rwa.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vertix.rwa.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAsset",
			Handler:    _Msg_RegisterAsset_Handler,
		},
		{
			MethodName: "AttestAsset",
			Handler:    _Msg_AttestAsset_Handler,
		},
		{
			MethodName: "MintRWA",
			Handler:    _Msg_MintRWA_Handler,
		},
		{
			MethodName: "TransferRWA",
			Handler:    _Msg_TransferRWA_Handler,
		},
		{
			MethodName: "SettleRWA",
			Handler:    _Msg_SettleRWA_Handler,
		},
		{
			MethodName: "UpdateRestrictions",
			Handler:    _Msg_UpdateRestrictions_Handler,
		},
		{
			MethodName: "SlashBond",
			Handler:    _Msg_SlashBond_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vertix/rwa/v1/tx.proto",
}
