// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package rwav1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_AssetRecord                 protoreflect.MessageDescriptor
	fd_AssetRecord_asset_id        protoreflect.FieldDescriptor
	fd_AssetRecord_issuer          protoreflect.FieldDescriptor
	fd_AssetRecord_name            protoreflect.FieldDescriptor
	fd_AssetRecord_description     protoreflect.FieldDescriptor
	fd_AssetRecord_status          protoreflect.FieldDescriptor
	fd_AssetRecord_oracle_pair     protoreflect.FieldDescriptor
	fd_AssetRecord_denom           protoreflect.FieldDescriptor
	fd_AssetRecord_bond            protoreflect.FieldDescriptor
	fd_AssetRecord_notional_minted protoreflect.FieldDescriptor
	fd_AssetRecord_allow_all       protoreflect.FieldDescriptor
	fd_AssetRecord_attested_price  protoreflect.FieldDescriptor
	fd_AssetRecord_attested_at     protoreflect.FieldDescriptor
	fd_AssetRecord_created_at      protoreflect.FieldDescriptor
	fd_AssetRecord_settled_at      protoreflect.FieldDescriptor
)

func init() {
	file_vertix_rwa_v1_types_proto_init()
	md_AssetRecord = File_vertix_rwa_v1_types_proto.Messages().ByName("AssetRecord")
	fd_AssetRecord_asset_id = md_AssetRecord.Fields().ByName("asset_id")
	fd_AssetRecord_issuer = md_AssetRecord.Fields().ByName("issuer")
	fd_AssetRecord_name = md_AssetRecord.Fields().ByName("name")
	fd_AssetRecord_description = md_AssetRecord.Fields().ByName("description")
	fd_AssetRecord_status = md_AssetRecord.Fields().ByName("status")
	fd_AssetRecord_oracle_pair = md_AssetRecord.Fields().ByName("oracle_pair")
	fd_AssetRecord_denom = md_AssetRecord.Fields().ByName("denom")
	fd_AssetRecord_bond = md_AssetRecord.Fields().ByName("bond")
	fd_AssetRecord_notional_minted = md_AssetRecord.Fields().ByName("notional_minted")
	fd_AssetRecord_allow_all = md_AssetRecord.Fields().ByName("allow_all")
	fd_AssetRecord_attested_price = md_AssetRecord.Fields().ByName("attested_price")
	fd_AssetRecord_attested_at = md_AssetRecord.Fields().ByName("attested_at")
	fd_AssetRecord_created_at = md_AssetRecord.Fields().ByName("created_at")
	fd_AssetRecord_settled_at = md_AssetRecord.Fields().ByName("settled_at")
}

var _ protoreflect.Message = (*fastReflection_AssetRecord)(nil)

type fastReflection_AssetRecord AssetRecord

func (x *AssetRecord) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AssetRecord)(x)
}

func (x *AssetRecord) slowProtoReflect() protoreflect.Message {
	mi := &file_vertix_rwa_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AssetRecord_messageType fastReflection_AssetRecord_messageType
var _ protoreflect.MessageType = fastReflection_AssetRecord_messageType{}

type fastReflection_AssetRecord_messageType struct{}

func (x fastReflection_AssetRecord_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AssetRecord)(nil)
}
func (x fastReflection_AssetRecord_messageType) New() protoreflect.Message {
	return new(fastReflection_AssetRecord)
}
func (x fastReflection_AssetRecord_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AssetRecord
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AssetRecord) Descriptor() protoreflect.MessageDescriptor {
	return md_AssetRecord
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AssetRecord) Type() protoreflect.MessageType {
	return _fastReflection_AssetRecord_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AssetRecord) New() protoreflect.Message {
	return new(fastReflection_AssetRecord)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AssetRecord) Interface() protoreflect.ProtoMessage {
	return (*AssetRecord)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AssetRecord) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.AssetId != "" {
		value := protoreflect.ValueOfString(x.AssetId)
		if !f(fd_AssetRecord_asset_id, value) {
			return
		}
	}
	if x.Issuer != "" {
		value := protoreflect.ValueOfString(x.Issuer)
		if !f(fd_AssetRecord_issuer, value) {
			return
		}
	}
	if x.Name != "" {
		value := protoreflect.ValueOfString(x.Name)
		if !f(fd_AssetRecord_name, value) {
			return
		}
	}
	if x.Description != "" {
		value := protoreflect.ValueOfString(x.Description)
		if !f(fd_AssetRecord_description, value) {
			return
		}
	}
	if x.Status != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Status))
		if !f(fd_AssetRecord_status, value) {
			return
		}
	}
	if x.OraclePair != "" {
		value := protoreflect.ValueOfString(x.OraclePair)
		if !f(fd_AssetRecord_oracle_pair, value) {
			return
		}
	}
	if x.Denom != "" {
		value := protoreflect.ValueOfString(x.Denom)
		if !f(fd_AssetRecord_denom, value) {
			return
		}
	}
	if x.Bond != "" {
		value := protoreflect.ValueOfString(x.Bond)
		if !f(fd_AssetRecord_bond, value) {
			return
		}
	}
	if x.NotionalMinted != "" {
		value := protoreflect.ValueOfString(x.NotionalMinted)
		if !f(fd_AssetRecord_notional_minted, value) {
			return
		}
	}
	if x.AllowAll != false {
		value := protoreflect.ValueOfBool(x.AllowAll)
		if !f(fd_AssetRecord_allow_all, value) {
			return
		}
	}
	if x.AttestedPrice != "" {
		value := protoreflect.ValueOfString(x.AttestedPrice)
		if !f(fd_AssetRecord_attested_price, value) {
			return
		}
	}
	if x.AttestedAt != nil {
		value := protoreflect.ValueOfMessage(x.AttestedAt.ProtoReflect())
		if !f(fd_AssetRecord_attested_at, value) {
			return
		}
	}
	if x.CreatedAt != nil {
		value := protoreflect.ValueOfMessage(x.CreatedAt.ProtoReflect())
		if !f(fd_AssetRecord_created_at, value) {
			return
		}
	}
	if x.SettledAt != nil {
		value := protoreflect.ValueOfMessage(x.SettledAt.ProtoReflect())
		if !f(fd_AssetRecord_settled_at, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AssetRecord) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vertix.rwa.v1.AssetRecord.asset_id":
		return x.AssetId != ""
	case "vertix.rwa.v1.AssetRecord.issuer":
		return x.Issuer != ""
	case "vertix.rwa.v1.AssetRecord.name":
		return x.Name != ""
	case "vertix.rwa.v1.AssetRecord.description":
		return x.Description != ""
	case "vertix.rwa.v1.AssetRecord.status":
		return x.Status != 0
	case "vertix.rwa.v1.AssetRecord.oracle_pair":
		return x.OraclePair != ""
	case "vertix.rwa.v1.AssetRecord.denom":
		return x.Denom != ""
	case "vertix.rwa.v1.AssetRecord.bond":
		return x.Bond != ""
	case "vertix.rwa.v1.AssetRecord.notional_minted":
		return x.NotionalMinted != ""
	case "vertix.rwa.v1.AssetRecord.allow_all":
		return x.AllowAll != false
	case "vertix.rwa.v1.AssetRecord.attested_price":
		return x.AttestedPrice != ""
	case "vertix.rwa.v1.AssetRecord.attested_at":
		return x.AttestedAt != nil
	case "vertix.rwa.v1.AssetRecord.created_at":
		return x.CreatedAt != nil
	case "vertix.rwa.v1.AssetRecord.settled_at":
		return x.SettledAt != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.AssetRecord"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.AssetRecord does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AssetRecord) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vertix.rwa.v1.AssetRecord.asset_id":
		x.AssetId = ""
	case "vertix.rwa.v1.AssetRecord.issuer":
		x.Issuer = ""
	case "vertix.rwa.v1.AssetRecord.name":
		x.Name = ""
	case "vertix.rwa.v1.AssetRecord.description":
		x.Description = ""
	case "vertix.rwa.v1.AssetRecord.status":
		x.Status = 0
	case "vertix.rwa.v1.AssetRecord.oracle_pair":
		x.OraclePair = ""
	case "vertix.rwa.v1.AssetRecord.denom":
		x.Denom = ""
	case "vertix.rwa.v1.AssetRecord.bond":
		x.Bond = ""
	case "vertix.rwa.v1.AssetRecord.notional_minted":
		x.NotionalMinted = ""
	case "vertix.rwa.v1.AssetRecord.allow_all":
		x.AllowAll = false
	case "vertix.rwa.v1.AssetRecord.attested_price":
		x.AttestedPrice = ""
	case "vertix.rwa.v1.AssetRecord.attested_at":
		x.AttestedAt = nil
	case "vertix.rwa.v1.AssetRecord.created_at":
		x.CreatedAt = nil
	case "vertix.rwa.v1.AssetRecord.settled_at":
		x.SettledAt = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.AssetRecord"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.AssetRecord does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AssetRecord) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vertix.rwa.v1.AssetRecord.asset_id":
		value := x.AssetId
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.issuer":
		value := x.Issuer
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.name":
		value := x.Name
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.description":
		value := x.Description
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.status":
		value := x.Status
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "vertix.rwa.v1.AssetRecord.oracle_pair":
		value := x.OraclePair
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.denom":
		value := x.Denom
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.bond":
		value := x.Bond
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.notional_minted":
		value := x.NotionalMinted
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.allow_all":
		value := x.AllowAll
		return protoreflect.ValueOfBool(value)
	case "vertix.rwa.v1.AssetRecord.attested_price":
		value := x.AttestedPrice
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.AssetRecord.attested_at":
		value := x.AttestedAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.created_at":
		value := x.CreatedAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.settled_at":
		value := x.SettledAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.AssetRecord"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.AssetRecord does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AssetRecord) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vertix.rwa.v1.AssetRecord.asset_id":
		x.AssetId = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.issuer":
		x.Issuer = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.name":
		x.Name = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.description":
		x.Description = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.status":
		x.Status = (AssetStatus)(value.Enum())
	case "vertix.rwa.v1.AssetRecord.oracle_pair":
		x.OraclePair = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.denom":
		x.Denom = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.bond":
		x.Bond = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.notional_minted":
		x.NotionalMinted = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.allow_all":
		x.AllowAll = value.Bool()
	case "vertix.rwa.v1.AssetRecord.attested_price":
		x.AttestedPrice = value.Interface().(string)
	case "vertix.rwa.v1.AssetRecord.attested_at":
		x.AttestedAt = value.Message().Interface().(*timestamppb.Timestamp)
	case "vertix.rwa.v1.AssetRecord.created_at":
		x.CreatedAt = value.Message().Interface().(*timestamppb.Timestamp)
	case "vertix.rwa.v1.AssetRecord.settled_at":
		x.SettledAt = value.Message().Interface().(*timestamppb.Timestamp)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.AssetRecord"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.AssetRecord does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AssetRecord) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vertix.rwa.v1.AssetRecord.attested_at":
		if x.AttestedAt == nil {
			x.AttestedAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.AttestedAt.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.created_at":
		if x.CreatedAt == nil {
			x.CreatedAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.CreatedAt.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.settled_at":
		if x.SettledAt == nil {
			x.SettledAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.SettledAt.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.asset_id":
		panic(fmt.Errorf("field asset_id of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.issuer":
		panic(fmt.Errorf("field issuer of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.name":
		panic(fmt.Errorf("field name of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.description":
		panic(fmt.Errorf("field description of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.status":
		panic(fmt.Errorf("field status of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.oracle_pair":
		panic(fmt.Errorf("field oracle_pair of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.denom":
		panic(fmt.Errorf("field denom of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.bond":
		panic(fmt.Errorf("field bond of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.notional_minted":
		panic(fmt.Errorf("field notional_minted of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.allow_all":
		panic(fmt.Errorf("field allow_all of message vertix.rwa.v1.AssetRecord is not mutable"))
	case "vertix.rwa.v1.AssetRecord.attested_price":
		panic(fmt.Errorf("field attested_price of message vertix.rwa.v1.AssetRecord is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.AssetRecord"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.AssetRecord does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AssetRecord) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vertix.rwa.v1.AssetRecord.asset_id":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.issuer":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.name":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.description":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.status":
		return protoreflect.ValueOfEnum(0)
	case "vertix.rwa.v1.AssetRecord.oracle_pair":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.denom":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.bond":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.notional_minted":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.allow_all":
		return protoreflect.ValueOfBool(false)
	case "vertix.rwa.v1.AssetRecord.attested_price":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.AssetRecord.attested_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.created_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "vertix.rwa.v1.AssetRecord.settled_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.AssetRecord"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.AssetRecord does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AssetRecord) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vertix.rwa.v1.AssetRecord", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AssetRecord) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AssetRecord) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AssetRecord) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AssetRecord) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AssetRecord)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.AssetId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Issuer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Description)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Status != 0 {
			n += 1 + runtime.Sov(uint64(x.Status))
		}
		l = len(x.OraclePair)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Denom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Bond)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NotionalMinted)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.AllowAll {
			n += 2
		}
		l = len(x.AttestedPrice)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.AttestedAt != nil {
			l = options.Size(x.AttestedAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CreatedAt != nil {
			l = options.Size(x.CreatedAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SettledAt != nil {
			l = options.Size(x.SettledAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AssetRecord)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.SettledAt != nil {
			encoded, err := options.Marshal(x.SettledAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x72
		}
		if x.CreatedAt != nil {
			encoded, err := options.Marshal(x.CreatedAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x6a
		}
		if x.AttestedAt != nil {
			encoded, err := options.Marshal(x.AttestedAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x62
		}
		if len(x.AttestedPrice) > 0 {
			i -= len(x.AttestedPrice)
			copy(dAtA[i:], x.AttestedPrice)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AttestedPrice)))
			i--
			dAtA[i] = 0x5a
		}
		if x.AllowAll {
			i--
			if x.AllowAll {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x50
		}
		if len(x.NotionalMinted) > 0 {
			i -= len(x.NotionalMinted)
			copy(dAtA[i:], x.NotionalMinted)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NotionalMinted)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.Bond) > 0 {
			i -= len(x.Bond)
			copy(dAtA[i:], x.Bond)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Bond)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.Denom) > 0 {
			i -= len(x.Denom)
			copy(dAtA[i:], x.Denom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Denom)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.OraclePair) > 0 {
			i -= len(x.OraclePair)
			copy(dAtA[i:], x.OraclePair)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OraclePair)))
			i--
			dAtA[i] = 0x32
		}
		if x.Status != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Status))
			i--
			dAtA[i] = 0x28
		}
		if len(x.Description) > 0 {
			i -= len(x.Description)
			copy(dAtA[i:], x.Description)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Description)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Name) > 0 {
			i -= len(x.Name)
			copy(dAtA[i:], x.Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Name)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Issuer) > 0 {
			i -= len(x.Issuer)
			copy(dAtA[i:], x.Issuer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Issuer)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.AssetId) > 0 {
			i -= len(x.AssetId)
			copy(dAtA[i:], x.AssetId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AssetId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AssetRecord)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AssetRecord: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AssetRecord: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AssetId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Issuer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Description = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				x.Status = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Status |= AssetStatus(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OraclePair", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OraclePair = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Denom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Bond = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NotionalMinted", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NotionalMinted = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AllowAll", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.AllowAll = bool(v != 0)
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AttestedPrice", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AttestedPrice = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AttestedAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.AttestedAt == nil {
					x.AttestedAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.AttestedAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 13:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.CreatedAt == nil {
					x.CreatedAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.CreatedAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 14:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SettledAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.SettledAt == nil {
					x.SettledAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.SettledAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_RWAParams                 protoreflect.MessageDescriptor
	fd_RWAParams_min_issuer_bond protoreflect.FieldDescriptor
	fd_RWAParams_mint_fee_rate   protoreflect.FieldDescriptor
	fd_RWAParams_settle_fee_rate protoreflect.FieldDescriptor
)

func init() {
	file_vertix_rwa_v1_types_proto_init()
	md_RWAParams = File_vertix_rwa_v1_types_proto.Messages().ByName("RWAParams")
	fd_RWAParams_min_issuer_bond = md_RWAParams.Fields().ByName("min_issuer_bond")
	fd_RWAParams_mint_fee_rate = md_RWAParams.Fields().ByName("mint_fee_rate")
	fd_RWAParams_settle_fee_rate = md_RWAParams.Fields().ByName("settle_fee_rate")
}

var _ protoreflect.Message = (*fastReflection_RWAParams)(nil)

type fastReflection_RWAParams RWAParams

func (x *RWAParams) ProtoReflect() protoreflect.Message {
	return (*fastReflection_RWAParams)(x)
}

func (x *RWAParams) slowProtoReflect() protoreflect.Message {
	mi := &file_vertix_rwa_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_RWAParams_messageType fastReflection_RWAParams_messageType
var _ protoreflect.MessageType = fastReflection_RWAParams_messageType{}

type fastReflection_RWAParams_messageType struct{}

func (x fastReflection_RWAParams_messageType) Zero() protoreflect.Message {
	return (*fastReflection_RWAParams)(nil)
}
func (x fastReflection_RWAParams_messageType) New() protoreflect.Message {
	return new(fastReflection_RWAParams)
}
func (x fastReflection_RWAParams_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_RWAParams
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_RWAParams) Descriptor() protoreflect.MessageDescriptor {
	return md_RWAParams
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_RWAParams) Type() protoreflect.MessageType {
	return _fastReflection_RWAParams_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_RWAParams) New() protoreflect.Message {
	return new(fastReflection_RWAParams)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_RWAParams) Interface() protoreflect.ProtoMessage {
	return (*RWAParams)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_RWAParams) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.MinIssuerBond != "" {
		value := protoreflect.ValueOfString(x.MinIssuerBond)
		if !f(fd_RWAParams_min_issuer_bond, value) {
			return
		}
	}
	if x.MintFeeRate != "" {
		value := protoreflect.ValueOfString(x.MintFeeRate)
		if !f(fd_RWAParams_mint_fee_rate, value) {
			return
		}
	}
	if x.SettleFeeRate != "" {
		value := protoreflect.ValueOfString(x.SettleFeeRate)
		if !f(fd_RWAParams_settle_fee_rate, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_RWAParams) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vertix.rwa.v1.RWAParams.min_issuer_bond":
		return x.MinIssuerBond != ""
	case "vertix.rwa.v1.RWAParams.mint_fee_rate":
		return x.MintFeeRate != ""
	case "vertix.rwa.v1.RWAParams.settle_fee_rate":
		return x.SettleFeeRate != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.RWAParams"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.RWAParams does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RWAParams) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vertix.rwa.v1.RWAParams.min_issuer_bond":
		x.MinIssuerBond = ""
	case "vertix.rwa.v1.RWAParams.mint_fee_rate":
		x.MintFeeRate = ""
	case "vertix.rwa.v1.RWAParams.settle_fee_rate":
		x.SettleFeeRate = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.RWAParams"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.RWAParams does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_RWAParams) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vertix.rwa.v1.RWAParams.min_issuer_bond":
		value := x.MinIssuerBond
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.RWAParams.mint_fee_rate":
		value := x.MintFeeRate
		return protoreflect.ValueOfString(value)
	case "vertix.rwa.v1.RWAParams.settle_fee_rate":
		value := x.SettleFeeRate
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.RWAParams"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.RWAParams does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RWAParams) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vertix.rwa.v1.RWAParams.min_issuer_bond":
		x.MinIssuerBond = value.Interface().(string)
	case "vertix.rwa.v1.RWAParams.mint_fee_rate":
		x.MintFeeRate = value.Interface().(string)
	case "vertix.rwa.v1.RWAParams.settle_fee_rate":
		x.SettleFeeRate = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.RWAParams"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.RWAParams does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RWAParams) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vertix.rwa.v1.RWAParams.min_issuer_bond":
		panic(fmt.Errorf("field min_issuer_bond of message vertix.rwa.v1.RWAParams is not mutable"))
	case "vertix.rwa.v1.RWAParams.mint_fee_rate":
		panic(fmt.Errorf("field mint_fee_rate of message vertix.rwa.v1.RWAParams is not mutable"))
	case "vertix.rwa.v1.RWAParams.settle_fee_rate":
		panic(fmt.Errorf("field settle_fee_rate of message vertix.rwa.v1.RWAParams is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.RWAParams"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.RWAParams does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_RWAParams) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vertix.rwa.v1.RWAParams.min_issuer_bond":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.RWAParams.mint_fee_rate":
		return protoreflect.ValueOfString("")
	case "vertix.rwa.v1.RWAParams.settle_fee_rate":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vertix.rwa.v1.RWAParams"))
		}
		panic(fmt.Errorf("message vertix.rwa.v1.RWAParams does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_RWAParams) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vertix.rwa.v1.RWAParams", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_RWAParams) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_RWAParams) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_RWAParams) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_RWAParams) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*RWAParams)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.MinIssuerBond)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MintFeeRate)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SettleFeeRate)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*RWAParams)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.SettleFeeRate) > 0 {
			i -= len(x.SettleFeeRate)
			copy(dAtA[i:], x.SettleFeeRate)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SettleFeeRate)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.MintFeeRate) > 0 {
			i -= len(x.MintFeeRate)
			copy(dAtA[i:], x.MintFeeRate)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MintFeeRate)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.MinIssuerBond) > 0 {
			i -= len(x.MinIssuerBond)
			copy(dAtA[i:], x.MinIssuerBond)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MinIssuerBond)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*RWAParams)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: RWAParams: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: RWAParams: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinIssuerBond", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MinIssuerBond = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MintFeeRate", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MintFeeRate = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SettleFeeRate", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SettleFeeRate = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vertix/rwa/v1/types.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetStatus is the lifecycle state of an RWA asset.
type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_UNSPECIFIED AssetStatus = 0
	AssetStatus_ASSET_STATUS_DRAFT       AssetStatus = 1
	AssetStatus_ASSET_STATUS_ATTESTED    AssetStatus = 2
	AssetStatus_ASSET_STATUS_ACTIVE      AssetStatus = 3
	AssetStatus_ASSET_STATUS_SETTLED     AssetStatus = 4
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_UNSPECIFIED",
		1: "ASSET_STATUS_DRAFT",
		2: "ASSET_STATUS_ATTESTED",
		3: "ASSET_STATUS_ACTIVE",
		4: "ASSET_STATUS_SETTLED",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_UNSPECIFIED": 0,
		"ASSET_STATUS_DRAFT":       1,
		"ASSET_STATUS_ATTESTED":    2,
		"ASSET_STATUS_ACTIVE":      3,
		"ASSET_STATUS_SETTLED":     4,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vertix_rwa_v1_types_proto_enumTypes[0].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_vertix_rwa_v1_types_proto_enumTypes[0]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_vertix_rwa_v1_types_proto_rawDescGZIP(), []int{0}
}

// AssetRecord is the registry entry for one RWA asset.
type AssetRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId        string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Issuer         string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status         AssetStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=vertix.rwa.v1.AssetStatus" json:"status,omitempty"`
	OraclePair     string                 `protobuf:"bytes,6,opt,name=oracle_pair,json=oraclePair,proto3" json:"oracle_pair,omitempty"`
	Denom          string                 `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
	Bond           string                 `protobuf:"bytes,8,opt,name=bond,proto3" json:"bond,omitempty"`
	NotionalMinted string                 `protobuf:"bytes,9,opt,name=notional_minted,json=notionalMinted,proto3" json:"notional_minted,omitempty"`
	AllowAll       bool                   `protobuf:"varint,10,opt,name=allow_all,json=allowAll,proto3" json:"allow_all,omitempty"`
	AttestedPrice  string                 `protobuf:"bytes,11,opt,name=attested_price,json=attestedPrice,proto3" json:"attested_price,omitempty"`
	AttestedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SettledAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
}

func (x *AssetRecord) Reset() {
	*x = AssetRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertix_rwa_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRecord) ProtoMessage() {}

// Deprecated: Use AssetRecord.ProtoReflect.Descriptor instead.
func (*AssetRecord) Descriptor() ([]byte, []int) {
	return file_vertix_rwa_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *AssetRecord) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetRecord) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AssetRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AssetRecord) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (x *AssetRecord) GetOraclePair() string {
	if x != nil {
		return x.OraclePair
	}
	return ""
}

func (x *AssetRecord) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *AssetRecord) GetBond() string {
	if x != nil {
		return x.Bond
	}
	return ""
}

func (x *AssetRecord) GetNotionalMinted() string {
	if x != nil {
		return x.NotionalMinted
	}
	return ""
}

func (x *AssetRecord) GetAllowAll() bool {
	if x != nil {
		return x.AllowAll
	}
	return false
}

func (x *AssetRecord) GetAttestedPrice() string {
	if x != nil {
		return x.AttestedPrice
	}
	return ""
}

func (x *AssetRecord) GetAttestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttestedAt
	}
	return nil
}

func (x *AssetRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AssetRecord) GetSettledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SettledAt
	}
	return nil
}

// RWAParams defines module governance parameters.
type RWAParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinIssuerBond string `protobuf:"bytes,1,opt,name=min_issuer_bond,json=minIssuerBond,proto3" json:"min_issuer_bond,omitempty"`
	MintFeeRate   string `protobuf:"bytes,2,opt,name=mint_fee_rate,json=mintFeeRate,proto3" json:"mint_fee_rate,omitempty"`
	SettleFeeRate string `protobuf:"bytes,3,opt,name=settle_fee_rate,json=settleFeeRate,proto3" json:"settle_fee_rate,omitempty"`
}

func (x *RWAParams) Reset() {
	*x = RWAParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertix_rwa_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RWAParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RWAParams) ProtoMessage() {}

// Deprecated: Use RWAParams.ProtoReflect.Descriptor instead.
func (*RWAParams) Descriptor() ([]byte, []int) {
	return file_vertix_rwa_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *RWAParams) GetMinIssuerBond() string {
	if x != nil {
		return x.MinIssuerBond
	}
	return ""
}

func (x *RWAParams) GetMintFeeRate() string {
	if x != nil {
		return x.MintFeeRate
	}
	return ""
}

func (x *RWAParams) GetSettleFeeRate() string {
	if x != nil {
		return x.SettleFeeRate
	}
	return ""
}

var File_vertix_rwa_v1_types_proto protoreflect.FileDescriptor

var file_vertix_rwa_v1_types_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x65, 0x72, 0x74, 0x69, 0x78, 0x2f, 0x72, 0x77, 0x61, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x78, 0x2e, 0x72, 0x77, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfd, 0x04, 0x0a,
	0x0b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x76, 0x65, 0x72, 0x74, 0x69, 0x78, 0x2e, 0x72, 0x77, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x70, 0x61,
	0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x50, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6f,
	0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0e, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x6e, 0x64, 0x12, 0x37,
	0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x69, 0x6e, 0x74, 0x65,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0e, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x4d, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x41, 0x6c, 0x6c, 0x12, 0x35, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0e, 0xd2, 0xb4,
	0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x52, 0x0d, 0x61, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x61,
	0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x08, 0xc8, 0xde,
	0x1f, 0x00, 0x90, 0xdf, 0x1f, 0x01, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x43, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x42, 0x08, 0xc8, 0xde, 0x1f, 0x00, 0x90, 0xdf, 0x1f, 0x01, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x43, 0x0a, 0x0a, 0x73, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x08, 0xc8, 0xde, 0x1f, 0x00, 0x90, 0xdf, 0x1f,
	0x01, 0x52, 0x09, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x22, 0xaf, 0x01, 0x0a,
	0x09, 0x52, 0x57, 0x41, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x36, 0x0a, 0x0f, 0x6d, 0x69,
	0x6e, 0x5f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0e, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x49, 0x6e, 0x74, 0x52, 0x0d, 0x6d, 0x69, 0x6e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x42, 0x6f,
	0x6e, 0x64, 0x12, 0x32, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x74, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0e, 0xd2, 0xb4, 0x2d, 0x0a, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x74, 0x46,
	0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x0f, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x66, 0x65, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0e, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x52,
	0x0d, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x46, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x2a, 0x91,
	0x01, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x18, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12,
	0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x52, 0x41,
	0x46, 0x54, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x54, 0x54, 0x45, 0x53, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x17, 0x0a, 0x13, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x53, 0x53, 0x45,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x44,
	0x10, 0x04, 0x42, 0xaf, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x78, 0x2e, 0x72, 0x77, 0x61, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x74, 0x69, 0x78, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2f, 0x76, 0x65, 0x72, 0x74, 0x69, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x78, 0x2f, 0x72, 0x77, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x77, 0x61, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x56, 0x52, 0x58, 0xaa, 0x02, 0x0d, 0x56, 0x65, 0x72, 0x74, 0x69, 0x78, 0x2e,
	0x52, 0x77, 0x61, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x56, 0x65, 0x72, 0x74, 0x69, 0x78, 0x5c,
	0x52, 0x77, 0x61, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x56, 0x65, 0x72, 0x74, 0x69, 0x78, 0x5c,
	0x52, 0x77, 0x61, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x0f, 0x56, 0x65, 0x72, 0x74, 0x69, 0x78, 0x3a, 0x3a, 0x52, 0x77, 0x61,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vertix_rwa_v1_types_proto_rawDescOnce sync.Once
	file_vertix_rwa_v1_types_proto_rawDescData = file_vertix_rwa_v1_types_proto_rawDesc
)

func file_vertix_rwa_v1_types_proto_rawDescGZIP() []byte {
	file_vertix_rwa_v1_types_proto_rawDescOnce.Do(func() {
		file_vertix_rwa_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_vertix_rwa_v1_types_proto_rawDescData)
	})
	return file_vertix_rwa_v1_types_proto_rawDescData
}

var file_vertix_rwa_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vertix_rwa_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vertix_rwa_v1_types_proto_goTypes = []interface{}{
	(AssetStatus)(0),              // 0: vertix.rwa.v1.AssetStatus
	(*AssetRecord)(nil),           // 1: vertix.rwa.v1.AssetRecord
	(*RWAParams)(nil),             // 2: vertix.rwa.v1.RWAParams
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_vertix_rwa_v1_types_proto_depIdxs = []int32{
	0, // 0: vertix.rwa.v1.AssetRecord.status:type_name -> vertix.rwa.v1.AssetStatus
	3, // 1: vertix.rwa.v1.AssetRecord.attested_at:type_name -> google.protobuf.Timestamp
	3, // 2: vertix.rwa.v1.AssetRecord.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: vertix.rwa.v1.AssetRecord.settled_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vertix_rwa_v1_types_proto_init() }
func file_vertix_rwa_v1_types_proto_init() {
	if File_vertix_rwa_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vertix_rwa_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vertix_rwa_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RWAParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vertix_rwa_v1_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vertix_rwa_v1_types_proto_goTypes,
		DependencyIndexes: file_vertix_rwa_v1_types_proto_depIdxs,
		EnumInfos:         file_vertix_rwa_v1_types_proto_enumTypes,
		MessageInfos:      file_vertix_rwa_v1_types_proto_msgTypes,
	}.Build()
	File_vertix_rwa_v1_types_proto = out.File
	file_vertix_rwa_v1_types_proto_rawDesc = nil
	file_vertix_rwa_v1_types_proto_goTypes = nil
	file_vertix_rwa_v1_types_proto_depIdxs = nil
}
